# Generated by Django 3.2.2 on 2021-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
